[profile.default]
solc = "0.8.13"
bytecode_hash = "none"
optimizer_runs = 1_000_000
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/contracts/",
]
match_path = "test/unit/*.sol"
verbosity = 3

[profile.integration]
match_path = "test/integration/*.sol"
eth_rpc_url = "https://api.avax.network/ext/bc/C/rpc"
block_number = 20817909

[profile.ci]
fuzz-runs = 10_000
