[profile.default]
solc = "0.8.18"
#via_ir = true
bytecode_hash = "none"
optimizer_runs = 1_000_000
libs = ['lib']
remappings = ["@openzeppelin/=lib/openzeppelin-contracts/contracts/"]
match_path = "test/unit/*.sol"
verbosity = 3
fs_permissions = [
    { access = "write", path = "./scripts/optimized-stable-mint-burn-key" },
    { access = "write", path = "./scripts/unoptimized-stable-mint-burn-key" },
]

[profile.default.model_checker]
#contracts = { "src/curve/stable/StablePair.sol" = [ "StablePair" ] }
engine = "chc"
timeout = 100000
targets = [
    "assert",
    "underflow",
    "overflow",
    "divByZero",
    "constantCondition",
    "popEmptyArray",
    "outOfBounds",
    "balance"
]

[profile.integration]
match_path = "test/integration/*.sol"

[profile.differential]
fs_permissions = [{ access = "read", path = "./reference/balancer-v2-monorepo" }]
match_path     = "test/differential/*.sol"

[profile.differential.fuzz]
runs = 10_000

[profile.ci.fuzz]
runs = 10_000

[rpc_endpoints]
avalanche = "https://api.avax.network/ext/bc/C/rpc"
polygon   = "https://polygon-rpc.com"

[fmt]
bracket_spacing   = true
wrap_comments     = false
number_underscore = "thousands"
int_types         = "long"
