[default]
solc = "0.8.13"
bytecode_hash = "none"
optimizer_runs = 1_000_000
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/contracts/",
]
match_contract = "Test"
verbosity = 3

[integration]
match_contract = "Integration"
eth_rpc_url = "https://cloudflare-eth.com"
block_number = 15165804

[ci]
fuzz-runs = 10_000
